image: maven:3.8.1-openjdk-15

stages:
  - build

build:
  stage: build
  script:
    - 'mvn clean install'
  only:
    - master
  artifacts:
    expire_in: 1d
    paths:
      - api.jar
      - conf/
      - api/
